export const skillIcons: Record<string, string> = {
  'JavaScript': 'javascript',
  'TypeScript': 'typescript',
  'Vue.js': 'vue',
  'React.js': 'react',
  'Next.js': 'nextjs',
  'Thymeleaf': 'thymeleaf',
  'JSP': 'jsp',
  'jQuery': 'jquery',
  'Java': 'java',
  'Spring Boot (eGov)': 'spring',
  'MyBatis': 'mybatis',
  'shadcn/ui': 'shadcn',
  'Styled-Components': 'styledcomponents',
  'Tailwind CSS': 'tailwind',
  'Webpack': 'webpack',
  'Vite': 'vite',
  'PostgreSQL': 'postgresql',
  'MySQL': 'mysql',
  'AWS EC2': 'aws',
  'Nginx': 'nginx',
  'Git': 'git',
  'SVN': 'svn',
  'Jira': 'jira',
  'Slack': 'slack',
  'MS Teams': 'msteams',
  'Figma': 'figma',
  'Zeplin': 'zeplin',
  'Adobe XD': 'xd',
  'Claude Code': 'claude',
  'Playwright MCP': 'playwright',
  'Shrimp Task Manager': 'shrimp',
}

export const siteConfig = {
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  name: '최인규',
  email: 'awdzx456@naver.com',
  github: 'https://github.com/dlsrbChoi',
  description: '프론트엔드에서 풀스택으로 성장한 개발자 최인규의 포트폴리오',
  phone: '',
  location: '',
  skillCategories: [
    {
      category: 'Front-end',
      items: ['JavaScript', 'TypeScript', 'Vue.js', 'React.js', 'Next.js', 'Thymeleaf', 'JSP', 'jQuery'],
    },
    {
      category: 'Back-end',
      items: ['Java', 'Spring Boot (eGov)', 'MyBatis'],
    },
    {
      category: 'Styling',
      items: ['shadcn/ui', 'Styled-Components', 'Tailwind CSS'],
    },
    {
      category: 'Build Tools',
      items: ['Webpack', 'Vite'],
    },
    {
      category: 'Database & Infra',
      items: ['PostgreSQL', 'MySQL', 'AWS EC2', 'Nginx'],
    },
    {
      category: 'Collaboration',
      items: ['Git', 'SVN', 'Jira', 'Slack', 'MS Teams', 'Figma', 'Zeplin', 'Adobe XD'],
    },
    {
      category: 'Productivity',
      items: ['Claude Code', 'Playwright MCP', 'Shrimp Task Manager'],
    },
  ],
}
